extends: [next/core-web-vitals, prettier]
rules:
  import/order:
    [
      error,
      {
        alphabetize: { order: asc },
        groups:
          ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
        pathGroups:
          [
            { pattern: '@/**', group: internal },
            { pattern: react, group: 'builtin', position: 'before' },
          ],
        pathGroupsExcludedImportTypes: [react],
        distinctGroup: true,
        newlines-between: always,
      },
    ]
