import clsx from 'clsx'
import { type AppType } from 'next/app'
import { Cabin } from 'next/font/google'
import Head from 'next/head'
import { Session } from 'next-auth'
import { SessionProvider } from 'next-auth/react'

import { api } from '@/utils/api'

// If loading a variable font, you don't need to specify the font weight
const inter = Cabin({ subsets: ['latin'] })

import './globals.css'

const SNAI: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <>
      <Head>
        <title>Snai</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SessionProvider session={session}>
        <main
          className={clsx(
            inter.className,
            'min-h-screen min-w-max flex flex-col justify-between'
          )}
        >
          <Component {...pageProps} />
        </main>
      </SessionProvider>
    </>
  )
}

export default api.withTRPC(SNAI)
