import { type NextPage } from 'next'
import Head from 'next/head'

import Footer from '@/components/footer'
import Header from '@/components/header'
import FacebookSDK from '@/facebook/sdk'

const Dashboard: NextPage = () => {
  const handleClick = () => {
    // @see https://developers.facebook.com/docs/sharing/reference/share-dialog/
    FB.ui({
      method: 'share',
      href: 'https://developers.facebook.com/docs/',
    })
  }

  return (
    <>
      <Head>
        <title>Snai</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main
        className={
          'min-h-screen min-w-[800px] text-[x-large] flex flex-col justify-between'
        }
      >
        <Header />
        <button
          onClick={() => {
            FB.login(function (response) {
              if (response.authResponse) {
                console.log('Welcome!  Fetching your information.... ')
                FB.api('/me', function (response) {
                  console.log('Good to see you, ' + response.name + '.')
                })
              } else {
                console.log('User cancelled login or did not fully authorize.')
              }
            })
          }}
        >
          fb login
        </button>
        <button
          onClick={() => {
            FB.api<'posts'>('/me', { fields: ['posts'] }, (response) => {
              console.log(response)
              if (response.posts) {
                FB.api<'posts'>(response.posts.paging.next, (response) => {
                  console.log('paginated response', response)
                  if (response.data) {
                    FB.api<'posts'>(response.paging.next, (response) => {
                      console.log('paginated response', response)
                      if (response.data) {
                        FB.api<'posts'>(response.paging.next, (response) => {
                          console.log('paginated response', response)
                        })
                      }
                    })
                  }
                })
              }
            })
          }}
        >
          get user data
        </button>
        <div>
          <button onClick={handleClick}>シェアする</button>
        </div>
        <Footer />
      </main>
    </>
  )
}

export default Dashboard
